export const allFeatureDefaults = [
  { featureKey: "attendance", featureName: "نظام الحضور والغياب", description: "تسجيل حضور وغياب الطلاب يومياً مع إمكانية تحديد الحالة (حاضر، غائب، متأخر، معذور) وإضافة ملاحظات وعرض سجل الحضور التاريخي", category: "management", isEnabled: true },
  { featureKey: "messaging", featureName: "المحادثات الداخلية", description: "نظام مراسلة فوري داخلي يتيح للمعلمين والمشرفين والطلاب التواصل المباشر مع بعضهم البعض داخل المنصة", category: "communication", isEnabled: true },
  { featureKey: "points_rewards", featureName: "النقاط والمكافآت", description: "نظام تحفيزي لمنح النقاط والشارات للطلاب على إنجازاتهم في الحفظ والسلوك والحضور مع لوحة شرف تعرض ترتيب المتميزين", category: "gamification", isEnabled: true },
  { featureKey: "schedules", featureName: "جدولة الحلقات", description: "تنظيم وعرض الجدول الأسبوعي لحلقات التحفيظ مع تحديد المعلم والوقت والمكان لكل حلقة", category: "management", isEnabled: true },
  { featureKey: "parent_portal", featureName: "بوابة ولي الأمر", description: "إنشاء تقارير دورية عن مستوى الطالب ومشاركتها مع ولي الأمر عبر رابط خاص دون الحاجة لتسجيل دخول", category: "communication", isEnabled: true },
  { featureKey: "mosque_map", featureName: "خريطة الجوامع", description: "عرض خريطة تفاعلية توضح مواقع الجوامع والمراكز القرآنية المسجلة في النظام", category: "visualization", isEnabled: false },
  { featureKey: "backup_export", featureName: "النسخ الاحتياطي والتصدير", description: "إمكانية تصدير بيانات النظام وإنشاء نسخ احتياطية لحماية البيانات من الفقدان", category: "data", isEnabled: true },
  { featureKey: "smart_alerts", featureName: "التنبيهات الذكية", description: "تنبيهات تلقائية تُرسل عند غياب الطالب المتكرر أو تراجع مستواه أو اقتراب مواعيد الامتحانات والمسابقات", category: "automation", isEnabled: true },
  { featureKey: "competitions", featureName: "المسابقات القرآنية", description: "تنظيم مسابقات قرآنية بين الطلاب مع تحديد السور والآيات وتسجيل النتائج والترتيب", category: "gamification", isEnabled: true },
  { featureKey: "advanced_reports", featureName: "التقارير المتقدمة", description: "تقارير تفصيلية وإحصائيات شاملة عن أداء الطلاب ونشاط المعلمين ومستوى التقدم في الحفظ", category: "analytics", isEnabled: true },
  { featureKey: "ratings", featureName: "التقييمات والأوسمة", description: "نظام تقييم أداء الطلاب ومنح الأوسمة والشارات التقديرية بناءً على مستوى الإنجاز", category: "gamification", isEnabled: true },
  { featureKey: "courses", featureName: "الدورات والشهادات", description: "إدارة الدورات التعليمية وإصدار شهادات الإتمام والتخرج للطلاب", category: "education", isEnabled: true },
  { featureKey: "library", featureName: "المكتبة الإسلامية", description: "مكتبة رقمية تحتوي على كتب ومراجع إسلامية متنوعة لدعم العملية التعليمية", category: "education", isEnabled: true },
  { featureKey: "knowledge_base", featureName: "موسوعة التجويد", description: "موسوعة شاملة لأحكام التجويد والآيات المتشابهة لمساعدة الطلاب والمعلمين", category: "education", isEnabled: true },
  { featureKey: "educational_content", featureName: "المحتوى التعليمي", description: "محتوى تعليمي تفاعلي يشمل دروس ومواد تعليمية متنوعة لدعم حفظ القرآن", category: "education", isEnabled: true },
  { featureKey: "graduation", featureName: "التخرج والمتابعة", description: "نظام متابعة الخريجين وتسجيل إنجازاتهم بعد إتمام الحفظ", category: "management", isEnabled: true },
  { featureKey: "family_system", featureName: "نظام الأسرة", description: "ربط حسابات أفراد الأسرة الواحدة لتسهيل المتابعة والتواصل", category: "communication", isEnabled: true },
  { featureKey: "whiteboard", featureName: "السبورة التفاعلية", description: "سبورة تفاعلية رقمية لاستخدامها في التدريس والشرح أثناء الحلقات", category: "education", isEnabled: true },
  { featureKey: "crisis_management", featureName: "إدارة الأزمات", description: "نظام لإدارة الأزمات والطوارئ والبدائل في حالات الغياب والظروف الطارئة", category: "management", isEnabled: true },
  { featureKey: "institutional", featureName: "التكامل المؤسسي", description: "نظام التكامل مع المؤسسات والجهات الخارجية ونقل البيانات بينها", category: "management", isEnabled: true },
  { featureKey: "floor_plan", featureName: "المخطط البصري", description: "عرض مخطط بصري لتوزيع القاعات والحلقات داخل الجامع أو المركز", category: "visualization", isEnabled: true },
  { featureKey: "id_cards", featureName: "الهويات ومسح QR", description: "إنشاء بطاقات هوية للطلاب والمعلمين مع رموز QR للتحقق السريع", category: "management", isEnabled: true },
];

export const featureRouteMap: Record<string, string[]> = {
  attendance: ["/api/attendance"],
  messaging: ["/api/messages"],
  points_rewards: ["/api/points", "/api/leaderboard"],
  schedules: ["/api/schedules"],
  parent_portal: ["/api/parent-portal"],
  smart_alerts: ["/api/smart-alerts"],
  competitions: ["/api/competitions"],
  advanced_reports: ["/api/advanced-reports"],
  ratings: ["/api/ratings"],
  courses: ["/api/courses", "/api/certificates"],
  library: ["/api/library"],
  knowledge_base: ["/api/tajweed", "/api/similar-verses"],
  educational_content: ["/api/educational-content"],
  graduation: ["/api/graduates"],
  family_system: ["/api/family"],
  crisis_management: ["/api/emergency", "/api/incidents"],
  institutional: ["/api/transfers"],
  id_cards: ["/api/id-cards"],
};
